# Generated by Django 4.2.6 on 2023-10-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/user/defult_image.png', null=True, upload_to='user/'),
        ),
    ]
