# Generated by Django 4.2.6 on 2023-10-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='user/defult_image.png', null=True, upload_to='user/'),
        ),
    ]
