# Generated by Django 4.2.6 on 2023-10-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'مرد'), ('FEMALE', 'زن')], default='MALE', max_length=20),
        ),
    ]
