# Generated by Django 4.2.6 on 2023-10-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_user_type_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ادمین', 'ادمین'), ('کاربر عادی', 'کاربر عادی')], default='USER', max_length=20),
        ),
    ]
