# Generated by Django 4.2.6 on 2023-10-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ادمین', 'ادمین'), ('کاربر عادی', 'کاربر عادی')], default='کاربر عادی', max_length=20),
        ),
    ]
