# Generated by Django 4.2.7 on 2023-11-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('phone_number1', models.CharField(max_length=100)),
                ('phone_number2', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
            ],
        ),
    ]
