# Generated by Django 4.2.7 on 2023-11-04 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='عنوان پست')),
                ('Image', models.ImageField(upload_to='blogeImage/', verbose_name='عکس')),
                ('Description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.CharField(max_length=200)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addProducts.cart')),
            ],
        ),
        migrations.CreateModel(
            name='DringModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='نام نوشیدنی')),
                ('Price', models.IntegerField(verbose_name='قیمت')),
                ('Image', models.ImageField(upload_to='dringImage/', verbose_name='عکس')),
                ('Description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'نوشیدنی',
                'verbose_name_plural': 'نوشیدنی ها',
            },
        ),
        migrations.CreateModel(
            name='foodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='نام غذا')),
                ('Price', models.IntegerField(verbose_name='قیمت')),
                ('Image', models.ImageField(upload_to='foodImage/', verbose_name='عکس')),
                ('Description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذا ها',
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('phone_number1', models.CharField(max_length=100)),
                ('phone_number2', models.CharField(blank=True, max_length=100, null=True)),
                ('tazkra_number', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('cart_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addProducts.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='drink',
            field=models.ManyToManyField(to='addProducts.dringmodel'),
        ),
        migrations.AddField(
            model_name='cart',
            name='food',
            field=models.ManyToManyField(to='addProducts.foodmodel'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
