# Generated by Django 4.2.7 on 2023-11-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addProducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
