# Generated by Django 4.2.7 on 2023-11-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addProducts', '0002_checkout_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='paid',
            new_name='ordered',
        ),
    ]
