# Generated by Django 4.2.7 on 2023-11-13 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addProducts', '0004_remove_cart_drink_remove_cart_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='tazkra_number',
        ),
    ]
