# Generated by Django 4.2.7 on 2023-11-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addProducts', '0006_cartitem_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='ali', max_length=500, null=True)),
                ('last_name', models.TextField(default='ahmadi', max_length=600, null=True)),
            ],
        ),
    ]
