# Generated by Django 4.2.7 on 2023-11-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addProducts', '0007_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='test1', max_length=100, null=True)),
                ('last_name', models.TextField(default='test1', max_length=100)),
            ],
        ),
    ]
