# Generated by Django 4.2.7 on 2023-11-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addProducts', '0008_test1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Test1',
        ),
    ]
