# Generated by Django 4.2.7 on 2023-11-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addProducts', '0009_delete_test_delete_test1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
