# Generated by Django 4.2.7 on 2023-11-14 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addProducts', '0010_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
